version: "3.8.1"

services:
  test-mysql:
    image: mysql:8.0
    container_name: test-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stepnote
      MYSQL_USER: stepnote
      MYSQL_PASSWORD: stepnote
    volumes:
      - ~/mysql-dataTest:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password