version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stepnote
      MYSQL_USER: stepnote
      MYSQL_PASSWORD: stepnote
    volumes:
      - ~/mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password